/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d2dbe1',
        'secondary-fixed': '#d1e4ff',
        'on-tertiary': '#ffffff',
        'on-surface': '#141d21',
        'surface-container': '#e6eff5',
        'on-secondary': '#ffffff',
        'on-primary-container': '#fdfcff',
        'secondary-fixed-dim': '#a0cafc',
        'on-primary-fixed-variant': '#00497c',
        'secondary-container': '#a3cdff',
        'inverse-surface': '#293236',
        'on-primary-fixed': '#001d36',
        'tertiary': '#904900',
        'primary-fixed-dim': '#9dcaff',
        'background': '#f3faff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'primary': '#005f9f',
        'surface-bright': '#f3faff',
        'primary-container': '#0078c7',
        'outline': '#707884',
        'surface-variant': '#dbe4e9',
        'surface-container-low': '#ecf5fb',
        'error-container': '#ffdad6',
        'secondary': '#36618d',
        'on-secondary-container': '#2a5782',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#d1e4ff',
        'surface-container-highest': '#dbe4e9',
        'on-secondary-fixed': '#001d35',
        'inverse-primary': '#9dcaff',
        'on-error': '#ffffff',
        'surface-container-high': '#e0e9ef',
        'surface-tint': '#0061a3',
        'error': '#ba1a1a',
        'surface': '#f3faff',
        'outline-variant': '#bfc7d4',
        'on-surface-variant': '#3f4752',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '48px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'margin-mobile': '16px',
        'gutter': '24px',
        'stack-sm': '8px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '14px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
